### PR TITLE
Master

### PR DESCRIPTION
**Pull request by obrien66**
I added words

### CODE REVIEW

**Comment by mattxwang** [comment]
I'll fill this out later. Avoid using programming terminology that sounds bad (i.e. dead badger).

**Comment by obrien66** [comment]
That was a prank. I wanted to see if you would have caught that.

On Saturday, 16 January 2016, Matthew Wang notifications@github.com wrote:

> I'll fill this out later. Avoid using programming terminology that sounds
> bad (i.e. dead badger).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/malsf21/robotics-club-website/pull/12#issuecomment-172267777
> .

## 

Cheers,

Nicholas O'Brien
Class of 2019
Mowbrays

**Comment by obrien66** [comment]
Badger is now gone.

On Saturday, 16 January 2016, Nicholas O’Brien nicholas.obrien@ucc.on.ca
wrote:

> That was a prank. I wanted to see if you would have caught that.
> 
> On Saturday, 16 January 2016, Matthew Wang <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > I'll fill this out later. Avoid using programming terminology that sounds
> > bad (i.e. dead badger).
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/malsf21/robotics-club-website/pull/12#issuecomment-172267777
> > .
> 
> ## 
> 
> Cheers,
> 
> Nicholas O'Brien
> Class of 2019
> Mowbrays

## 

Cheers,

Nicholas O'Brien
Class of 2019
Mowbrays

**Comment by mattxwang** [comment]
This is a public repo, and I do check your code.

**Comment by obrien66** [comment]
I just remembered that it's now ucc.on.ca as well. Don't worry. Won't
happen again.

On Saturday, 16 January 2016, Matthew Wang notifications@github.com wrote:

> This is a public repo, and I do check your code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/malsf21/robotics-club-website/pull/12#issuecomment-172267919
> .

## 

Cheers,

Nicholas O'Brien
Class of 2019
Mowbrays

**Pull request closed without merging**
